# architecture
arch: vit_base
enc_arch: MAEViTEncoder
dec_arch: MAEViTDecoder
dec_arch_c: ContrastiveDecoder

# wandb
proj_name: mae3d_contrastive_picai
run_name: mae3d_contrastive_picai
wandb_id: 1qr6vuvr
disable_wandb: 0
wandb_proj: 

# dataset
dataset: prostate
task: Task2201_picai
overview_task: Task2201_picai
data_path: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/nnUNet_raw_data/${task}
overviews_dir: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/overviews/UNet/overviews/${task}
json_list: 'dataset2.json'
data_seed: 12345
ts_fold: 0

# output
output_dir: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/models/${run_name}
ckpt_dir: ${output_dir}/ckpts

# data preprocessing
roi_x: 32
roi_y: 256
roi_z: 256
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
spatial_dim: 3
cache_rate: 1.
image_shape: [32, 256, 256]
num_channels: 3

# trainer
trainer_name: MAE3DContrastiveTrainer
batch_size: 4
vis_batch_size: 1
start_epoch: 0
warmup_epochs: 10
epochs: 500
workers: 8
num_threads: ${workers}
pretrain:
resume: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/models/mae3d_contrastive_picai/ckpts/checkpoint_0199.pth.tar
manual_test:
start_from:
get_best_model:
evaluate:
picai_dataloader: true

# model
patchembed: 'PatchEmbed3D'
pos_embed_type: 'sincos'
mask_ratio: 0.8
input_size: ${roi_x}
patch_size: 16
in_chans: 3
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
decoder_embed_dim: 384
decoder_depth: 8
decoder_num_heads: 12

# contrastive decoder
out_channels: 512

# optimizer
type: adamw
lr: 6.4e-3
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# logging
vis_freq: 10
save_freq: 100
print_freq: 5

# distributed processing
gpu: 0
dist_url: # 'tcp://localhost:10001'
world_size: 1
multiprocessing_distributed: false
dist_backend: nccl
distributed:
rank: 0
ngpus_per_node:

# randomness
seed:

# debugging
debug: false

num_classes: 2