# architecture
arch: UNet
enc_arch: 
dec_arch: 
contrastive_decoder_type: 'MLP'

# wandb
proj_name: contrastive_byol
model_name: UNet
run_name: unet_byol_mae
wandb_id: 
disable_wandb: 0
wandb_proj: 

# dataset
dataset: prostate
task: Task2201_picai
#overview_task: Task2210_picai_prostate158_only_negative #Para entrenar denoise
overview_task: Task2201_picai #Para evaluar
overviews_valid_dir: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/overviews/UNet/overviews/${task}
data_path: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/nnUNet_raw_data/${task}
overviews_dir: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/overviews/UNet/overviews/${task}
json_list: 'dataset2.json'
data_seed: 12345
ts_fold: 0

# output
output_dir: /mnt/researchers/denis-parra/datasets/jfacuse_workdir/models/${run_name}
ckpt_dir: ${output_dir}/ckpts

# data preprocessing
roi_x: 32
roi_y: 256
roi_z: 256
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
spatial_dim: 3
cache_rate: 1.
image_shape: [32, 256, 256]
num_channels: 3

# trainer
trainer_name: BYOLTrainer
batch_size: 8
val_batch_size: 1
start_epoch: 0
warmup_epochs: 10
epochs: 300
initial_tau: 0.996
workers: 8
num_threads: ${workers}
pretrain:
resume: 
start_from:  
manual_test: false
picai_dataloader: true
get_best_model: false
evaluate: false
calc_metrics: false
eval_test: false

# model
patch_size: 16
in_chans: 3
feature_size: 16
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
out_chans: 3
model_strides: [[2, 2, 2], [1, 2, 2], [1, 2, 2], [1, 2, 2], [2, 2, 2]]
model_features: [32, 64, 128, 256, 512, 1024]

# noise
noise_std: 0.2
noise_shape: 16
noise_multiplier: 4

# augmentation
augmentation: MAE

# contrastive decoder
out_channels: 512

# contrastive loss
rot_weight: 0
recon_weight: 1.0
contrast_weight: 1.0

# drop
drop_path: 0.1
# tricks
mixup: 0.
cutmix: 0.
label_smoothing: 0.

# optimizer
type: adamw
lr: 6.4e-3
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# logging
vis_freq: 40
save_freq: 40
print_freq: 5

# distributed processing
gpu: 0
dist_url: # 'tcp://localhost:10001'
world_size: 1
multiprocessing_distributed: false
dist_backend: nccl
distributed:
rank: 0
ngpus_per_node:

# randomness
seed:

# debugging
debug: false

num_classes: 2