# architecture
arch: UNet
enc_arch: 
dec_arch: 

# wandb
proj_name: denoise_picai
model_name: UNet
run_name: ${proj_name}_${arch}_${dataset}
wandb_id: 
disable_wandb: 
wandb_proj: denoise_prostate

# dataset
dataset: prostate
task: Task2201_picai
#overview_task: Task2210_picai_prostate158_only_negative #Para entrenar denoise
overview_task: Task2201_picai #Para evaluar
data_path: /mnt/workspace/jfacuse/prostate/workdir/nnUNet_raw_data/${task}
overviews_dir: /mnt/workspace/jfacuse/prostate/workdir/results/UNet/overviews/${overview_task}
overviews_valid_dir: /mnt/workspace/jfacuse/prostate/workdir/results/UNet/overviews/${task}
json_list: 'dataset2.json'
data_seed: 12345
ts_fold: 0

# output
output_dir: /mnt/workspace/jfacuse/test_MedMAE_picai/${run_name}
ckpt_dir: ${output_dir}/ckpts

# data preprocessing
roi_x: 32
roi_y: 256
roi_z: 256
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1
spatial_dim: 3
cache_rate: 1.
image_shape: [32, 256, 256]
num_channels: 3

# trainer
trainer_name: DenoiseTrainer
batch_size: 2
vis_batch_size: 1
start_epoch: 0
warmup_epochs: 10
epochs: 300
workers: 8
num_threads: ${workers}
pretrain:
resume:
start_from:  
manual_test: false
picai_dataloader: true
get_best_model: false
evaluate: false
calc_metrics: false

# model
patch_size: 16
in_chans: 3
feature_size: 16
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
out_chans: 3
model_strides: [[2, 2, 2], [1, 2, 2], [1, 2, 2], [1, 2, 2], [2, 2, 2]]
model_features: [32, 64, 128, 256, 512, 1024]

# noise
noise_std: 0.2
noise_shape: 16
noise_multiplier: 4

# drop
drop_path: 0.1
# tricks
mixup: 0.
cutmix: 0.
label_smoothing: 0.

# optimizer
type: adamw
lr: 6.4e-3
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# logging
vis_freq: 10
save_freq: 100
print_freq: 5

# distributed processing
gpu: 2
dist_url: # 'tcp://localhost:10001'
world_size: 1
multiprocessing_distributed: false
dist_backend: nccl
distributed:
rank: 0
ngpus_per_node:

# randomness
seed:

# debugging
debug: false

num_classes: 2